---

- name: Ensure the data directory is present
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../data/"
    state: directory
    mode: "{{ directory_permissions }}"
  run_once: yes
  delegate_to: localhost

- name: Write switch-inventory
  ansible.builtin.template:
    src: switch_inventory.j2
    dest: "{{ playbook_dir }}/../data/{{ switch_inventory_filename }}"
    mode: "{{ file_permissions }}"
  run_once: yes
  delegate_to: localhost
