---

- name: Write switch-inventory
  ansible.builtin.template:
    src: switch_inventory.j2
    dest: "{{ playbook_dir }}/../data/{{ switch_inventory_filename }}"
    mode: 0644
  run_once: yes
  delegate_to: localhost
