---

- name: "Gather VLANs of master-switch"
  gather_facts: no
  hosts:
    - site_a

  pre_tasks:
    - name: Gather facts of master-switch
      setup:
      when:
        - master_switch is defined
        - master_switch|bool

  roles:
    - role: list_vlans
      vars:
        vlan_db_filename: master.yml
      when:
        - master_switch is defined
        - master_switch|bool
