---

name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'mboehm21.switch-setup'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'mboehm21.switch-setup'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} mboehm21.switch-setup
